### ISSUE TITLE
getting Permission Denial: opening provider com.android.fileexplorer.provider.FileExplorerFileProvider

### ISSUE THREAD

**Issue by worldwidee** [Nikhil1999/uri-to-file#11]
Hello thanks for the package
I'am receiving Intents by using https://pub.dev/packages/receive_intent. But it returns URI. My code snip:
```dart
  void listenReceivedSharingFiles() async {
    _intentDataStreamSubscription =
        ReceiveIntent.receivedIntentStream.listen((Intent? intent) async {
      if (intent?.extra != null) {
        if ((await Permission.storage.request()).isGranted) {
          File file = await toFile(intent!.uriString!);
        }
      }
    }, onError: (err) {
      // Handle exception
    });
  }
```
Basically i get error with this uriString

```dart
  var file = await toFile(
      "content://com.mi.android.globalFileexplorer.myprovider/external_files/Download/sample_CustomersOrders.xml");
```

Error:
java.lang.SecurityException: Permission Denial: opening provider com.android.fileexplorer.provider.FileExplorerFileProvider from ProcessRecord{2d24274 19076:com.tamtechnology.venture/u0a551} (pid=19076, uid=10551) that is not exported from UID 10151
Unhandled Exception: PlatformException(error, Permission Denial: opening provider com.android.fileexplorer.provider.FileExplorerFileProvider from ProcessRecord{2d24274 19076:com.tamtechnology.venture/u0a551} (pid=19076, uid=10551) that is not exported from UID 10151, null, java.lang.SecurityException: Permission Denial: opening provider com.android.fileexplorer.provider.FileExplorerFileProvider from ProcessRecord{2d24274 19076:com.tamtechnology.venture/u0a551} (pid=19076, uid=10551) that is not exported from UID 10151

![Capture](https://github.com/Nikhil1999/uri-to-file/assets/49057380/fe3506d8-d743-4d42-8ba3-e18b89ffc5c4)

**Comment by Nikhil1999** [comment]
@worldwidee Have you tried opening the same file in the example app of (uri-to-file)
I think there is some issue with the uriString that you are passing. May be it is incorrect you can try implementing the uni links package that might help

**Comment by worldwidee** [comment]
Hi
users need to share files to my app. and this file must be of xml type. I used all libraries with receive_intent for this. https://pub.dev/packages/receive_intent successfully gives me the uri but I get a permission error when converting to the uri. Can I do this with uni_links?

**Comment by Nikhil1999** [comment]
Hi @worldwidee 
Yes, You can do this with uni_links 
Let me know if you still facing this issue 

Closing this as fixed
