### ISSUE TITLE
Update Packages

### ISSUE THREAD

**Issue by poorankharol** [Nikhil1999/uri-to-file#12]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':uri_to_file' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by armanivers** [comment]
+1

**Comment by bhaskarraj** [comment]
I am also getting the same issue.  I am using     `ext.kotlin_version = '1.7.10'`

**Comment by Julietttead** [comment]
Hi,

I have also getting the same issue. With version of kotlin equals to : 1.9.10.

I tried to update kotlin version of uri_to_file package from Android Studio but the compilation continues to fail.

Best regards,

**Comment by Nikhil1999** [comment]
Hi @poorankharol @armanivers @bhaskarraj @hadrienm 
I have updated the package to v1.0.0
Please use the latest version this will fix your kotlin version issue
Let me know if you still face the same issue

Sorry for the delay guys
